### ISSUE TITLE
Remove this repo?

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/wallet-template#1]
Wallet-template is merged into a subproject of bitcoinj. Does this repo have any use since then?
I noticed some people fork this repo to extend wallet-template. I assume they're doing it on an outdated version.

**Comment by mikehearn** [comment]
There's virtually no changes, AFAIK. The intention of this repo was indeed to be forkable and more easily accessible than the submodule. OTOH having the submodule means IntelliJ will auto-refactor the code when I rename things and move stuff around, and it ensures it keeps building.

So the idea was: have this as the last stable release version, and then when we do a bitcoinj upstream release, just copy the code across.

**Comment by schildbach** [comment]
Ah sorry I forgot.

**Comment by msgilligan** [comment]
Now that Mike is gone and this repo is not being synced (or used, I suspect) we should reconsider removing it.
