### ISSUE TITLE
Invalid generated address

### ISSUE THREAD

**Issue by pierre03** [bitcoinj/wallet-template#2]
Hi,

I have tested on faucet site, but i get this error with the generated address:

Invalid Testnet3 address: 12EFpSPF1F5kgXWvGNLNsBYTBZ9pqurFQX

**Comment by schildbach** [comment]
Yes, it's a mainnet address.

**Comment by pierre03** [comment]
Thank you, it works.
But can you identify them?

**Comment by schildbach** [comment]
Mainnet addresses start with "1", "2" or "3".
