### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JoaoGFarias** [bitcoinj/wallet-template#3]
Using the Github search, I've found only three files with any license information.
Is there an official license for the whole repository?

<img width="779" alt="screen shot 2017-04-10 at 19 41 14" src="https://cloud.githubusercontent.com/assets/1585655/24885602/cb67279c-1e25-11e7-8c8a-2b2df02fc1f0.png">

**Comment by schildbach** [comment]
Afaik wallet-template is licensed under APLv2, except for some files copied from elsewhere. The interpolators are such exceptions.
