### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [bitcoinj/wallet-template#6]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by schildbach** [comment]
Duplicate of https://github.com/bitcoinj/bitcoinj/issues/1976 and others.

Please stop spamming.

**Comment by Neustradamus** [comment]
@schildbach: No it is not a duplicate:
- https://github.com/bitcoinj/wallet-template/search?q=spongycastle&unscoped_q=spongycastle

**Comment by Neustradamus** [comment]
@schildbach: Can you reopen and close when it will be solved?
